# Generated by Django 5.2.6 on 2025-10-03 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0002_alter_department_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
