# Generated by Django 5.2.6 on 2026-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='check_num',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
