# Generated by Django 5.2.6 on 2025-10-06 06:37

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='documents/default.pdf', upload_to=documents.models.document_upload_path),
        ),
    ]
