# Generated by Django 5.2.6 on 2026-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.IntegerField(editable=False),
        ),
    ]
