# Generated by Django 5.2.6 on 2025-10-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
